name: COI action

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: setup go
          uses: actions/setup-go@v4
          with:
            go-version: '1.22.x'
        - name: generate examples
          run: go run main.go -f examples/example.go
        - name: build binary
          run: go build -o bin/coi main.go
        - uses: stefanzweifel/git-auto-commit-action@v5
          with:
              commit_message: "[AUTO] from github action"
              branch: add/workflows
              commit_options: '--no-verify --signoff'
              repository: .
              skip_dirty_check: true    
              skip_fetch: true 
              skip_checkout: true
              disable_globbing: true
              create_branch: true
        